package com.mobike.mobikeapp.model.c;

public class b
{
  public static final String A = "operation_card_data";
  public static final String B = "operation_icon_data";
  public static final String C = "operation_config_version";
  public static final String D = "operation_config_city";
  public static final String E = "operation_config_country_key";
  public static final String F = "operation_config_currency_key";
  public static final int G = 0;
  public static final String H = "guide_page";
  public static final String I = "first_booking_bike";
  public static final String J = "first_unlock_success";
  public static final String K = "scanner_show_times";
  public static final String L = "poi_history_prefs";
  public static final String M = "poi_keywords";
  public static final String N = "ride_prefs";
  public static final String O = "order_id";
  public static final String P = "orderId";
  public static final String Q = "isRecordingTrack";
  public static final String R = "track_distance";
  public static final String S = "track_string";
  public static final String T = "qrcode";
  public static final String U = "http://www.mobike.com/download/app.html?b=";
  public static final String V = "appeal_ticket_id";
  public static final String W = "bike_issue.jpg";
  public static final String X = "pay_order.jpg";
  public static final String Y = "key";
  public static final String Z = "webview_url";
  public static final int a = 1001000;
  public static final String aA = "com.mobike.action.checkupdate";
  public static final String aB = "com.mobike.action.wxpaysuccess";
  public static final String aC = "WEBVIEW_RED_PACKET_SURPRISE_INFO";
  public static final String aD = "WEBVIEW_SURPRISE_KEY";
  public static final String aE = "refund_amount";
  public static final String aF = "refund_code";
  public static final String aG = "refund_message";
  public static final String aH = "mobike://";
  public static final String aI = "900002114";
  public static final String aJ = "TYPE";
  public static final String aK = "PUSH";
  public static String aL = "rideResult";
  public static String aM = "defaultPrefer";
  public static String aN = "park_help";
  public static String aO = "/img/shars.jpg";
  public static String aP = "bike_id";
  public static String aQ = "ride_info";
  public static String aR = "assist_bike_location";
  public static String aS = "bike_type_bar";
  public static String aT = "search_center";
  public static final String aU = "red_packet_value";
  public static final String aV = "1187161213178428#kefuchannelapp32172";
  public static final String aW = "32172";
  public static final String aX = "kefuchannelimid_908598";
  public static final int aY = 999;
  public static final int aZ = 998;
  public static final String aa = "webview_title";
  public static final String ab = "webview_menu";
  public static final String ac = "WEBVIEW_FOR_SURPRISE_RED_PACKET_KEY";
  public static final String ad = "WEBVIEW_HIDE_LOADING_KEY";
  public static final String ae = "SURPRISE_ZIP_DONE";
  public static final String af = "SURPRISE_ZIP_DONE_KEY";
  public static final String ag = "IS_SURPRISE_POCKET_OPEN";
  public static final String ah = "PRECIOUS_ICON_NAME";
  public static final String ai = "PRECIOUS_ICON_DATA_KEY";
  public static final String aj = "wx822295c9333f22d8";
  public static final String ak = "f8385fd38cbe379d85245e762010356a";
  public static final String al = "1236691302";
  public static final String am = "93418a2926e54f9aaae572c378de0841";
  public static final String an = "3171513705";
  public static final String ao = "41e7ece97e31247304af15dd90dc65fb";
  public static final String ap = "com.umeng.share";
  public static final String aq = "1105067195";
  public static final String ar = "m11Yl4Tlso01HyKA";
  public static final String as = "psHXZYB5r5infN89bk0tFCChj";
  public static final String at = "VJVvVVsSC4dAJNrXZqIf4CtEaaobaqVfDKBU0BQoH1f8B29HRA";
  public static final String au = "http://mobike.com/wp-content/themes/mobike/img/logos/mobike-logo-icon-3-preview.png";
  public static final String av = "201874";
  public static final String aw = "28401c0964f04a72a14c812d6132fcef";
  public static final String ax = "3bf66e42db1e4fa9829b955cc300b737";
  public static final String ay = "com.mobike.action.getQRCode";
  public static final String az = "com.mobike.action.unlockBike";
  public static final int b = 14;
  public static final String ba = "redPacketInfo";
  public static final String bb = "pk_live_P8PIJN8yZUaIreN0eo3ifpU9";
  public static final String bc = "975F217D3B704D13872E6E7D2F7B2721";
  public static final int c = 47;
  public static final int d = 57;
  public static final int e = 110;
  public static final int f = 500;
  public static final int g = 500;
  public static final int h = 10;
  public static final int i = 10;
  public static final int j = 15;
  public static final int k = 10;
  public static final int l = 8;
  public static final int m = 15;
  public static final int n = 140;
  public static final int o = 1;
  public static final double p = 2.0D;
  public static final double q = 50.0D;
  public static final float r = 9.7F;
  public static final String s = "#";
  public static final String t = ",";
  public static final String u = ";";
  public static final char v = '^';
  public static final String w = "position";
  public static final String x = "settings_prefs";
  public static final String y = "bike_type_data";
  public static final String z = "service_bounds_data";
}


/* Location:              /WORK/jd-gui-windows-1.4.0/classes2-dex2jar.jar!/com/mobike/mobikeapp/model/c/b.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       0.7.1
 */